### ISSUE TITLE
Upgrade helper doesn't respect comments from earlier versions

### ISSUE THREAD

**Issue by Peter-Vincent** [bonsai-rx/bonsai#1097]
We've upgraded some computers from Bonsai 2.6 to 2.7.  

For files that were edited in 2.6, if there are commented bits of code that contain any node that has changed from 2.6 to 2.7, those comments are no longer respected.  For example, if there is a workflow that includes a subject in at at some point that was commented out in 2.6, in 2.7 that workflow is no longer commented out after that subject.  See attached workflow:

[disabled_nodes_simple.zip](https://github.com/bonsai-rx/bonsai/files/9902156/disabled_nodes_simple.zip)

Opening the workflow using Bonsai v2.6 several comments are visible. Opening the workflow with Bonsai v2.7 will re-enable originally disabled subject nodes.

It would be ideal if there is a quick program that parses through the old files from 2.6 and prepares them for 2.7.

**Comment by glopesdev** [comment]
@Peter-Vincent I was finally able to repro this issue. It affects only a combination of comments and certain updated nodes such as subjects, but it is symptomatic of a subtle but general issue with the update mechanism.

We will fix it in the patch release.
