### ISSUE TITLE
Consider publishing a fork of LibGit2Sharp to solve native dependency loader

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/bonsai#1548]
It would be quite useful to have access to the [`LibGit2Sharp`](https://www.nuget.org/packages/LibGit2Sharp) library as a package in custom extensions. The main hurdle is to make sure all native dependencies can be automatically found.

[There is an open PR](https://github.com/libgit2/libgit2sharp/pull/2020) to try and address this issue, but since it seems there is no response from project maintainers, it would be great if we could turn the PR into a custom package that people could easily install and access via extensions.

**Comment by glopesdev** [comment]
This will not be needed if we resolve #1549 instead. Just did a quick test and it seems to work.
