### ISSUE TITLE
This is a proxy for the unknown type 'Bonsai.Scripting.ExpressionTransform'. Please install any missing packages or replace this operator.

### ISSUE THREAD

**Issue by SamuelLiebana** [bonsai-rx/bonsai#1557]
We have been experiencing the following error on updating from Bonsai 2.6.3 to 2.8:

"This is a proxy for the unknown type 'Bonsai.Scripting.ExpressionTransform'. Please install any missing packages or replace this operator"

This is when we try to run a Neurophotometrics script using the packages that they recommend downloading (Bonsai Starter Pack and Neurophotometrics.Design).

**Comment by SamuelLiebana** [comment]
Just managed to solve the issue by installing the Bonsai Scripting Library package. We recommend that either the starter pack or Neurophotometric's manual are updated to reflect this extra step in the set-up process to get Neurophotometrics rigs working with the new version of Bonsai.

**Comment by glopesdev** [comment]
@SamuelLiebana The Bonsai Scripting package is no longer a mandatory dependency of the starter pack. This is by design as discussed in #1558. We have no control over the Neurophotometrics system so unfortunately cannot help with updating their documentation.
