### ISSUE TITLE
[Bug] Python Source/Transform node

### ISSUE THREAD

**Issue by PedroACFerreira** [bonsai-rx/bonsai#1565]
Bit of a random bug, but, if instead of selecting Python Source/Transform from  Source >> Scripting.IronPython, you search for it using the search bar, and then select it from there, specifically by double clicking, the Python Source node that gets pushed to the workflow instead of coming with the default script, e.g :
```
@returns(int)
def generate():
   yield 0
```
comes with specifically the last word you typed into the search bar. Bit confusing for people newer to Bonsai on how to get the node working if that happens. 

OS: Windows 10
Bonsai 2.8.0, persisted on 2.8.1 
Bonsai IronPython 2.7.5

**Comment by PedroACFerreira** [comment]
Manually updated to Bonsai 2.8.1, no longer happens.

**Comment by bruno-f-cruz** [comment]
It's a feature, not a bug!. All searches in the toolbox use anything after the initial space as an input to the main property of the node. In the case of python transforms, that property is the actual code inside of the operator. This is extremely useful for other operators. For instance, if you type "int 5" it creates an int source and populates the value with 5. Similarly, if you type "expressiontran it*5" it creates an expressiontransform with a string: it*5 in its expression.
