### ISSUE TITLE
Bonsai Crashing after pressing stop when using two AudioCapture nodes in parallel

### ISSUE THREAD

**Issue by BenjaminEscribano** [bonsai-rx/bonsai#1693]
Hi,

when I use two AudioCapture nodes with different microphones Bonsai will crash after pressing stop.

Has ayone been able to resolve a similar issue?

Thx!

**Comment by BenjaminEscribano** [comment]
![AudioCapture](https://github.com/bonsai-rx/bonsai/assets/67735766/f46fa6b6-9b54-4532-ab29-209cdc5a7383)

**Comment by bruno-f-cruz** [comment]
This is already being followed in the discussions. Let's just keep discussing there. Add whatever new information you have. (Have you tested with a different pair of mic models? Other pc? When does it crash?) thanks!
