### ISSUE TITLE
When the workflow/subject categories are empty, dragging them to the workflow results in `NullReferenceException`

### ISSUE THREAD

**Issue by PathogenDavid** [bonsai-rx/bonsai#1759]
Noticed while monkeying around trying to reproduce https://github.com/bonsai-rx/bonsai/issues/1591

When the Workflow/Subject toolbox categories are empty (as pictured below), it's possible to drag them to the Workflow. Doing so results in a `NullReferenceException` in [`GetToolboxElementCategory`](https://github.com/bonsai-rx/bonsai/blob/50627731bfbf265a08e06f22ce6e4ec85053dc9d/Bonsai.Editor/GraphView/WorkflowGraphView.cs#L128-L138) due to `elementCategories` being `null`.

![image](https://github.com/bonsai-rx/bonsai/assets/278957/16348234-33cc-4ecf-9d93-c03692df8680)

Considering they stop being draggable once they have members, I assume they aren't supposed to be draggable ever.

**Comment by glopesdev** [comment]
Good catch!
