### ISSUE TITLE
GratingSpecification does not pass trials to CreateGratingTrial

### ISSUE THREAD

**Issue by banchan86** [bonsai-rx/bonsai#1832]
While going through the BonVision docs to reproduce the examples I noticed this issue.

Following the first example on this page
https://bonvision.github.io/pages/08-GratingSeries/

does not produce the intended sequence of gratings, GratingSequence simply reproduces what is defined in CreateGratingTrial.

This issue is also referenced in

https://github.com/orgs/bonsai-rx/discussions/1684

Probably related, the 2AFC demo in Bonvision examples repo no longer works (same issue does not produce GratingSpecification trials)

https://github.com/bonvision/examples/tree/master/Demos/OriDiscrimination

Workflow attached and tested in Bonsai 2.8.0 and Bonsai 2.8.3

[grating-stimuli.zip](https://github.com/user-attachments/files/15519612/grating-stimuli.zip)

**Comment by glopesdev** [comment]
@banchan86 can you reopen this issue on https://github.com/bonvision/BonVision? Unfortunately we cannot transfer issues across organizations.
