### ISSUE TITLE
NuGet package testing feed deployed with portable zip release

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/bonsai#1911]
I am assuming this happens due to the presence of the `NUGET_API_URL` environment variable here:

https://github.com/bonsai-rx/bonsai/blob/3464e656adf0c6354be1c98e5877d40e0e94adfb/.github/workflows/create-portable-zip.py#L33

This makes a lot of sense for testing deployments and CI, but for full releases it might be best to make sure everyone is pulling packages from the stable NuGet feed and not accidentally installing nightly builds from the testing feed.

Probably also related to https://github.com/bonsai-rx/bonsai/issues/1881

**Comment by glopesdev** [comment]
Actually, just realizing that the URL here is pointing to the stable NuGet feed, so it maybe is just the name which is misleading. Should probably be renamed simply as `nuget.org`.

**Comment by PathogenDavid** [comment]
> Should probably be renamed simply as `nuget.org`, at least for a full deployment?

I missed this comment before I created my PR. My intent was it to simply not be present when targeting the production NuGet.org instance.

Adding it shouldn't be necessary either way unless someone removed it from their machine-wide NuGet.config, but I like to think if they did that they probably had a decent reason (like they use a caching proxy for NuGet.org.) We could opt-out of the machine-wide NuGet.config with a `<clear />`, which might not be unreasonable for Bonsai (especially the portable zip), but feels unnecessary and would annoy people who actually want the machine-wide config.

**Comment by glopesdev** [comment]
This is also a good point. I will go ahead and merge the PR as-is, and we can review and test machine-wide settings on NuGet-naive machines when we move definitively away from MyGet.
