### ISSUE TITLE
Avoid displaying commit hash in AboutBox and workflow file version

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/bonsai#1912]
This probably makes sense for dev builds, but I think it might be confusing especially for people versioning workflows to suddenly have the git hash come up for full releases.

I think this currently is picked up only in two places in `WorkflowBuilder` and `AboutBox` respectively:

https://github.com/bonsai-rx/bonsai/blob/3464e656adf0c6354be1c98e5877d40e0e94adfb/Bonsai.Core/WorkflowBuilder.cs#L204

https://github.com/bonsai-rx/bonsai/blob/3464e656adf0c6354be1c98e5877d40e0e94adfb/Bonsai.Editor/AboutBox.cs#L63

In both cases we can condition on `BUILD_KIND_OFFICIAL_RELEASE` to decide how to assemble the version string.

**Comment by PathogenDavid** [comment]
I was surprised when you originally expressed interest in leaving it in the workflow files but wasn't gonna question it 😅

I think it's not totally unreasonable for it to be in the about box, but there's other ways to find it so I'm OK either way.
