### ISSUE TITLE
Consider allowing non-single inputs to be passed to Visualizer

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/bonsai#1925]
Related to #1896 

In addition to a 0-input overload for Visualizer, we should also consider allowing >1 inputs to pass simultaneous sequences to the operator. This would offer quite a nicer experience when making generalizable IncludeWorkflows visualizers.

**Comment by glopesdev** [comment]
@bruno-f-cruz The `Defer` operator already supports all of this, so if we adopt #1896 this would be automatically solved.

**Comment by glopesdev** [comment]
Duplicate of #1896
