### ISSUE TITLE
Consider removing --no-restore flag from dotnet test and pack CI steps

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/bonsai#1927]
While setting up similar CI for another project I noticed this PR: https://github.com/dotnet/cli/pull/8100. I have tested it locally and it seems to function as advertised, so perhaps we could remove `--no-restore` from the following steps:

https://github.com/bonsai-rx/bonsai/blob/d746ebeb72d103f0b357ff46911e04706f0348a2/.github/workflows/Bonsai.yml#L122

https://github.com/bonsai-rx/bonsai/blob/d746ebeb72d103f0b357ff46911e04706f0348a2/.github/workflows/Bonsai.yml#L127

**Comment by PathogenDavid** [comment]
I was aware of `--no-build` implying `--no-restore`, but I feel it's better to be explicit here. Not being explicit looks like a mistake at first glance if you don't know about one flag implying the other. These flags aren't typically used when invoking `dotnet` manually, so I wouldn't want to rely on the reader knowing about this.

**Comment by glopesdev** [comment]
@PathogenDavid I agree with this rationale, it was definitely useful when I was reading this with no context to understand what has happening.

I can see the logic behind them doing the logical implication as it would be weird to ask for `--no-build` and still restore, but fine keeping it as-is.

**Comment by PathogenDavid** [comment]
Yeah, I definitely think the behavior of the `dotnet` command makes sense (especially for people running commands interactively.) For me it's 100% a clarity thing
