### ISSUE TITLE
Unexpected Reactive.Timer behavior

### ISSUE THREAD

**Issue by jonnew** [bonsai-rx/bonsai#1947]
Using Bonsai 2.8.5, the behavior on the Timer node appears to be fundamentally different depending on the value of the Period property. 

- If I specify a period of 1 second, the node produces a count value every second.
- If I leave Period set to 00:00:00 a single count of 0 is produced and the sequence then terminates. This does not mesh with the description of the Period parameter.
- If I write a very short period (.e. g 00:00:00.0001000) the timer will produce two values 0 and 1 and then stops.  Again this does not fit with the description of Period

This feels like a race condition to me. e.g. the thread performing checks if counter has passed a due period is using eqaulity operator instead of >=.

**Comment by glopesdev** [comment]
@jonnew The special value 0 in the period is interpreted as a non-periodic timer. This is the only choice which was our design choice in the very early days of Bonsai. This one has a longer history which is indeed questionable, but a true period of 0 would mean an infinite loop which would hang the thread and be harmful in almost every case and inclusive might hang the termination thread.

Regarding the behavior with very small intervals this operator is implemented directly by Rx so we cannot control its internal behavior. It is known that small periods below 10ms do not work properly, but if there are explicitly race conditions unfortunately in this case they will have to be resolved upstream.

**Comment by jonnew** [comment]
@glopesdev I understand the intended behavior of the special 0 value as it is documented in the `Period`s Description attribute. However, the operator does not behave in this way when the `Period` is set to 0. It produces one element and then the sequence ends. 

Regarding short periods -- unfortunate but ok.

**Comment by glopesdev** [comment]
@jonnew there are two properties in the timer source, `DueTime` and `Period`. `DueTime` is always used and specifies the delay until the first timer value is produced. Following the first value, if `Period` is greater than zero, the timer recurs with the specified periodicity.

That means that if the Timer is left with its default values of 0 and 0 for `DueTime` and `Period` respectively, this will create a non-periodic timer that fires its first value immediately upon subscription and then terminates, as you described. This behavior is also implemented by the corresponding Rx operator `Observable.Timer` and not something we introduced.

If you look in the source code of the Timer node you will see that it calls directly into the corresponding Rx operator.

**Comment by glopesdev** [comment]
Actually I realize the documentation for the `Period` operator is wrong, and it does not reflect the behavior of the operator. I will flag it for review in the next milestone and we either introduce a nullable property as in `Shaders.Timer` or we change the documentation to correctly describe the current behavior.
