### ISSUE TITLE
isKeyDown was not found in the current build context

### ISSUE THREAD

**Issue by meganloz** [bonsai-rx/bonsai#2021]
I am trying to run this script that has previously worked. I use KeyDown to initiate the fiber recording and the shock timer, but the first instance of isKeyDown returns this error. Has anyone experienced this?

[bonsai_fearcond.txt](https://github.com/user-attachments/files/17065241/bonsai_fearcond.txt)

![image](https://github.com/user-attachments/assets/7cd1c6e1-2129-4950-8a32-37b8533de469)
![image](https://github.com/user-attachments/assets/005cd809-77a8-4100-bf2e-7498b372c101)
![image](https://github.com/user-attachments/assets/7cb5ee74-373a-4afe-a060-aa1147b0f447)
[bonsai_fearcond.txt](https://github.com/user-attachments/files/17065241/bonsai_fearcond.txt)

**Comment by bruno-f-cruz** [comment]
Heya!

There appears to be a missing subject that is being referenced without being created in the first place. If it was running in its previous state I would advise you to compare and add the missing code.
