### ISSUE TITLE
Incorrect header. Parameter name usb buffer

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/bonsai#639]
**[Original report](https://bitbucket.org/horizongir/bonsai/issue/639) by Bruno Cruz (Bitbucket: [bruno_cruz](https://bitbucket.org/bruno_cruz), ).**

----------------------------------------

Using bonsai 2.4.

When recording  with rhd2000 I get the error mentioned in the title. Any ideas what could be happening?

I have no additional message in the console. And the bug seems to happen randomly usually after recording for more than 15min. 

Best,

B

![](https://bitbucket.org/repo/7bGd5/images/1238155251-image.png)

**Comment by n-loureiro** [comment]
On bonsai 2.5.2 I'm still getting this error. 
It's weird that some times it runs for hours without any problem and other times it crashes with this error after a couple of minutes.

Any suggestion on how to solve this issue?
