### ISSUE TITLE
CSharpSource does not find script when project is moved.

### ISSUE THREAD

**Issue by aalmada** [bonsai-rx/bonsai#673]
When the first CSharpSource node is created, Bonsai creates an "Extensions" folder and adds the scripts inside of it.
If the project is moved to another location, Bonsai cannot load the script and it seems there's no way to tell its location. Even if the "Extensions" folder is placed at the same relative location.

**Comment by glopesdev** [comment]
Have you copied the .csproj file as well? It is needed for the Bonsai bootstrapper to look for Extensions. What is the error message that shows up in the command window?

**Comment by aalmada** [comment]
Sorry, I did not notice the .csproj in the middle of the other files. Copying it did fix the problem. Thanks!
