### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by plusplusi** [bonsai-rx/bonsai#695]
I'm following the instuction in this project to get calibration file

https://github.com/HiveTracker/bonsai-interface/tree/calibration

When I opened Bonsai.Examples.RoomVR.bonsai file and ran
There's an error :This is a proxy for the unknown type' Bonsai.Shaders.RenderFrame'. Please install any missing packages or replace this operator.
What's the problem, thanks!

**Comment by glopesdev** [comment]
@plusplusi do you mind [opening an issue](https://github.com/HiveTracker/bonsai-interface/issues/new/choose) on the HiveTracker repository? This repository is for issues with the bonsai compiler and IDE only.
