### ISSUE TITLE
Add Bonsai boilerplate for "add-ons"

### ISSUE THREAD

**Issue by amchagas** [bonsai-rx/bonsai#709]
@glopesdev Don't know if you have something like this already (or if I am using the proper nomenclature), but it would be nice to have a minimal CS project(package?) that works with bonsai? 

From what I remember on my initial attempts, I could only getting something working when using the nodes already present in Bonsai (v2.4 I think) and renaming/saving them, but don't know if this is good practice/best way to do it?

**Comment by glopesdev** [comment]
This already exists as part of the Bonsai installation using Visual Studio templates. From the installer menu, you can choose **Options** > **Register Visual Studio Extensions**, or after the installation, you can go to the windows start menu and choose **Install Bonsai VS Extensions**.

This will install a new project template for Visual Studio which is exactly a barebones ready to build and debug project template.
