### ISSUE TITLE
Allow adding a custom description to an operator without creating a group

### ISSUE THREAD

**Issue by jfrazao** [bonsai-rx/bonsai#750]
Like in the main workflow when you select the background you have access to the externalized properties, maybe you could have also description field.

**Comment by glopesdev** [comment]
Can you outline the proposal in more detail, ideally with pros/cons breakdown and suggested implementations?

Simply adding a `Description` property to every single operator has the obvious disadvantage of complicating the object model of the language, adding unnecessary mutable state and fields to all operators in the compiler, and risking obfuscating accidentally the functionality of nodes.

For example, an alternative implementation might implement this as a decorator on top of existing nodes, e.g. the same way as enable/disable nodes work. The icon and all properties of the current node would need to be automatically exposed while making the description field optional and much more self-contained.

This solution would probably require generalizing the decorator pattern for nodes more broadly to avoid the proliferation of case-by-case exceptions which might even resolve other clunky issues such as the `Value` property in `BinaryOperatorBuilder` and all its unique behaviors (e.g. see #137).

**Comment by svrks** [comment]
I had posted about this on the Google forum a couple days ago. I like the concept of a decorator. I was looking for an equivalent of commenting in non-object oriented programing for each node. The primary aim would be to have easier teachability and collaborative design.

**Comment by glopesdev** [comment]
This is also related to the proposal in #1170.
