### ISSUE TITLE
Consider adding the output of a process when called from "startProcess"

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/bonsai#760]
Related to https://groups.google.com/g/bonsai-users/c/8O_9454DJj4
Basically, after running a command using `startProcess`, it would be useful to keep outputting values from the process. This would be especially useful for termination codes that might be dependent on the successful termination of the command.

Thanks!

**Comment by glopesdev** [comment]
> it would be useful to keep outputting values from the process

What exactly do you mean by this? Is the goal to read from the redirected output of the process, or just read the exit code?

If it is just the exit code, the current implementation of `StartProcess` should already return this upon completion of the command: https://github.com/bonsai-rx/bonsai/blob/510b9688040f50094123156bf4da4bee8bdef7d6/Bonsai.System/IO/StartProcess.cs#L50-L55

**Comment by bruno-f-cruz** [comment]
Sorry, you are right. I was doing something wrong in the Arduino CLI side that I thought would crash the program and send a fail "1" code but it actually returned a success, "0" code. I went back to it and after some tinkering, it is working now! 
Thanks,
B
