### ISSUE TITLE
Crash on start due to package management issue

### ISSUE THREAD

**Issue by jonnew** [bonsai-rx/bonsai#764]
Bonsai Version: 2.6
OS: Windows 10

This has happened to me a few times now. I don't know the underlying cause so I'm just reporting some behavior. Basically, sometimes when I manage packages in using the Package Manager, the editor is permanently prevented from working due to some missing dependencies. Here is a screenshot of the console when this happens:

![image](https://user-images.githubusercontent.com/1429475/108731163-214ba000-74e1-11eb-9b57-26f332e542ab.png)

I have to quickly print screen to capture this message because the console immediately closes after it is displayed. The only solution I have found for getting around this is to completely purge and reinstall Bonsai. I'm not sure if there is pattern in terms of the particular packages, etc that I'm installing to cause this behavior. I will add to this thread if I notice something.

**Comment by jonnew** [comment]
Update: its not just the editor, the Package Manager also cannot be opened. Here is the console from that situation:
![image](https://user-images.githubusercontent.com/1429475/108731782-c0709780-74e1-11eb-890c-ee2b1c23b431.png)

**Comment by nbonacchi** [comment]
Deleting the Bonsai.config file should restore Bonsai to default configuration and recreate the default Bonsai.config file.
You'll lose the installed packages though.

Usually to deploy and reproduce a specific Bonsai configuration just 4 files are needed: here's an example ([link](https://github.com/int-brain-lab/iblscripts/tree/save_video_test/deploy/videopc/bonsai/bin)) NB: this is on a testing branch and once merged to master link might probably not work 

Hope it helps

**Comment by glopesdev** [comment]
This is possibly related to #755.
