### ISSUE TITLE
Display full range of data values in ScalarHistogramVizualizer

### ISSUE THREAD

**Issue by znamensk** [bonsai-rx/bonsai#766]
Currently ScalarHistogramVizualizer is hardcoded to display the histogram for values 0 to 255. As the result it is impractical for looking at image histograms of 12 bit cameras. 

https://github.com/bonsai-rx/bonsai/blob/bda7c01edcc3879e732288d58800ea5ae1c3d80b/Bonsai.Vision.Design/ScalarHistogramVisualizer.cs#L40

**Comment by glopesdev** [comment]
Good point, we should probably also fix the `ImageHistogram` operator not to assume 8-bit depth, or allow fixing the maximum range:

https://github.com/bonsai-rx/bonsai/blob/bda7c01edcc3879e732288d58800ea5ae1c3d80b/Bonsai.Vision/ImageHistogram.cs#L14

**Comment by glopesdev** [comment]
@znamensk In the meantime, you can use `Histogram1D` as a workaround. Here you can configure how many bins and the bin ranges in a way which is compatible with 12-bit images.
