### ISSUE TITLE
Install 2.6.2 failed - Unable to load the service index for source https://api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by LWitter** [bonsai-rx/bonsai#777]
Hi all,

I'm encountering an issue when trying to install. No matter what I try I constantly get the following error:
_Unable to load the service index for source
https://api.nuget.org/v3/index.json_

From various sources I get that this might have to do with proxy settings, but I don't have any proxy server connections set up.

- Deleting the Nuget config file and/or directory => No effect
- I checked whether the file can be reached => Accessible with Chrome and with IE
- I checked windows registry for proxy settings, and set to bypass => didn't change anything (https://stackoverflow.com/questions/41185443/nuget-connection-attempt-failed-unable-to-load-the-service-index-for-source)
- I checked the proxy settings in windows configuration => Nothing specified
- I appended default proxy-bypass settings to the nuget config file => Issue persists.

I'm at a complete loss what else to try. Hopefully someone has encountered this problem and has been as stuck as I am (and resolved it), or someone has another idea to try.

Laurens

**Comment by bruno-f-cruz** [comment]
Hi, 
Some users have reported a similar issue when trying to install in Win7, if this is your case you might want to check this post:
https://groups.google.com/g/bonsai-users/c/IVgr6CaqrJU/m/bVNu5WfNBgAJ
Cheers,

**Comment by LWitter** [comment]
Oh, that solved it immediately. It was indeed on win7. I already figured out it could have something to do with secure communications, but just could not get it to work. Cost me two days.....
Many, many thanks for guiding me to this solution!
