### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by caniko** [bonsai-rx/bonsai#803]
Labs that have the expertise to run their experimental setups on Linux should account for a robust tool such as Bonsai to be functional on it. Can we get Linux support?

Seems to be a clear and short path to victory [here](https://stackoverflow.com/questions/13103360/how-to-write-programs-in-c-sharp-net-to-run-them-on-linux-wine-mono). Going to give it a shot in my off time.

**Comment by glopesdev** [comment]
This is already supported as of version 2.5.1:
https://github.com/bonsai-rx/bonsai/releases/tag/2.5.1

See the following forum question for more info on how to install:
https://groups.google.com/g/bonsai-users/c/C9DPHTBFd1Y/m/xmeBS5rZEgAJ

Feel free to follow up in the forums if you have any difficulties getting it to run. So far we have tested up to Ubuntu 20.04.

**Comment by dprotter** [comment]
For anyone who ends up here via a web search, here is a link to the most up-to-date documentation for Bonsai on linux:

[https://github.com/orgs/bonsai-rx/discussions/1101](https://github.com/orgs/bonsai-rx/discussions/1101)
