### ISSUE TITLE
subject names cut off in workflow display

### ISSUE THREAD

**Issue by edmundchong** [bonsai-rx/bonsai#835]
When Subject names get too long, they get truncated in the workflow display.

1. Would it be helpful in the display, to add "..." at the end of the displayed name to indicate that the actual subject name is longer?
2. A minor, possibly related issue is that when subject names include underscores, they seem to get cut off earlier in the display: see image below--the full name in the second example below (image) is abcdef_ghijkl_mno

![image](https://user-images.githubusercontent.com/18076139/145696273-90cd9b40-2c9b-4dbc-b1ce-76e2d59a117e.png)

**Comment by glopesdev** [comment]
More options for breaking identifiers have been introduced in #1694.
