### ISSUE TITLE
leave & save PythonTransform script when clicking Ctrl+S

### ISSUE THREAD

**Issue by orena1** [bonsai-rx/bonsai#847]
Hi,
It might be good to automatically save and exit PythonTransform script when clicking Ctrl+S (or some other shortcut)
Corrently when clicking Ctrl+S it adds DC3

![Screenshot_20220216_173618](https://user-images.githubusercontent.com/8983713/154368786-02bdd764-9c4f-4940-b8a6-6299362a70ca.png)

**Comment by glopesdev** [comment]
Shortcuts for exiting scripting editors were introduced in https://github.com/bonsai-rx/bonsai/commit/437bb070142c4d101294970056b4863eec49e1db.

The shortcut for existing and saving all modifications to the script is `Ctrl+Enter`.
